### PR TITLE
include lib for linux arm64 

### PR DESCRIPTION
**Pull request by sorumehta**

### CODE REVIEW

**Comment by sorumehta** [comment]
Does the generated file need renaming?

**Comment by Shinmera** [comment]
What's the output of `uname -m`?

**Comment by sorumehta** [comment]
@Shinmera The output of `uname -m` is `aarch64`, but the new filename (after your change) is `libglfw-lin-arm64.so`. That okay?

**Comment by sorumehta** [comment]
@Shinmera The PR is ready

**Comment by Shinmera** [comment]
Thanks a lot! Sorry for the roundabout back-and-forth

**Comment by sorumehta** [comment]
No sweat buddy

**Pull request merged**
